services:

  services:
    image: lfmontesc/services:latest
    mem_limit: 800m
    ports:
      - "8080:8080"
    networks:
      - lfmontesc-network
    
  reviews:
    image: lfmontesc/reviews:latest
    mem_limit: 800m
    ports:
      - "8081:8081"
    networks:
      - lfmontesc-network

  hotels:
    image: lfmontesc/hotels:latest
    mem_limit: 800m
    ports:
      - "8082:8082"
    networks:
      - lfmontesc-network

networks:
  lfmontesc-network: